import { v4 as uuid } from "uuid";
export const products = [
    {
        _id: uuid(),
        title:"Drum",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Drum.jpg',  
        price: "5000",
        categoryName: "Drum",
      },
      {
        _id: uuid(),
        title:"Flute",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Flute.jpg',  
        price: "3000",
        categoryName: "Flute",
      },
      {
        _id: uuid(),
        title:"Drum",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Drum.jpg',  
        price: "6000",
        categoryName: "Drum",
      },
      {
        _id: uuid(),
        title:"Drum",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Drum.jpg',  
        price: "1200",
        categoryName: "Drum",
      },
      {
        _id: uuid(),
        title:"Trumpet",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Trumpet.jpg',  
        price: "5000",
        categoryName: "Trumpet",
      },
      {
        _id: uuid(),
        title:"Trumpet",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Trumpet.jpg',  
        price: "5300",
        categoryName: "Trumpet",
      },
      
      {
        _id: uuid(),
        title:"Flute",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Flute.jpg',  
        price: "5000",
        categoryName: "Flute",
      },
      {
        _id: uuid(),
        title:"Flute",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Flute.jpg',  
        price: "5000",
        categoryName: "Flute",
      },
      {
        _id: uuid(),
        title:"Drum",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Drum.jpg',  
        price: "5000",
        categoryName: "Drum",
      },
      {
        _id: uuid(),
        title:"Flute",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Flute.jpg',  
        price: "5000",
        categoryName: "Flute",
      },
      {
        _id: uuid(),
        title:"Trumpet",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Trumpet.jpg',  
        price: "5000",
        categoryName: "Trumpet",
      },
      {
        _id: uuid(),
        title:"Drum",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Drum.jpg',  
        price: "5199",
        categoryName: "Drum",
      },
      {
        _id: uuid(),
        title:"Trumpet",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Trumpet.jpg',  
        price: "5000",
        categoryName: "Trumpet",
      },
      {
        _id: uuid(),
        title:"Flute",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Flute.jpg',  
        price: "5000",
        categoryName: "Flute",
      },
      {
        _id: uuid(),
        title:"Trumpet",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Trumpet.jpg',  
        price: "5000",
        categoryName: "Trumpet",
      },
];
